name: Check Main Branch and Deploy

on:
  push:
    branches:
      - main

jobs:
  check-main-branch-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
        
      - name: Set remote URL for gh-pages branch
        run: |
          git remote set-url origin https://github.com/${{ github.repository }}.git

      - name: Configure git
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"

      - name: Build and deploy
        env:
          GH_TOKEN: ${{ secrets.GH_PAGES_TOKEN }}

      - name: Install dependencies
        run: npm install --force

      - name: Build and deploy
        env:
          MY_EMAIL: ritu.raj.ingale@gmail.com
          MY_NAME: anti-yREX
        run: git config --global user.email $MY_EMAIL && git config --global user.name $MY_NAME && git config -l && npm run deploy
