name: Check Main Branch and Deploy

on:
  push:
    branches:
      - main

jobs:
  check-main-branch-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
        
      - name: show username
        run: |
          echo "hello: ${{ ghpages.HELLO }}"

      - name: Set remote URL for gh-pages branch
        run: |
          git remote set-url origin https://${{ secrets.GH_USERNAME }}:${{ secrets.GH_PAGES_TOKEN }}@github.com/${{ github.repository }}.git

      - name: Configure git
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"

      - name: Install dependencies
        run: npm install --force

      - name: Build and deploy
        run: git config -l && npm run deploy
